### ISSUE TITLE
Multiple Activity.All in single orchestration ce ?

### ISSUE THREAD

**Issue by richardjharding** [mikhailshilkov/DurableFunctions.FSharp#11]
Should it be possible to have multiple Activity.All declared in a single orchestration?

I modified one of the samples (FanOutFanIn) 
```
let workflow = orchestrator {
    let! items =
      ["Tokyo"; "Seattle"; "London"]
      |> List.map (Activity.call hardWork)
      |> Activity.all

    let! items2 =
      ["Tokyo"; "Seattle"; "London"]
      |> List.map (Activity.call hardWork)
      |> Activity.all

    

    // returns "Worked hard on Tokyo!, Worked hard on Seattle!, Worked hard on London!"
    return String.concat ", " items
  }
```

and the orchestration status was stuck in "Running" - as a follow up should be able to make additional 

Activity.call after a Activity.all completes?

When I try that I get the exception "Multi threading detected" although I can't immediately work out whats causing that (I'm not awaiting any tasks, or performing IO)

Should I be placing that "Activity.all" in a sub orchestration do you think?

**Comment by mikhailshilkov** [comment]
@richardjharding Thanks for reporting! This fix is underway.
