### ISSUE TITLE
Eternal orchestrations

### ISSUE THREAD

**Issue by richardjharding** [mikhailshilkov/DurableFunctions.FSharp#13]
Is it possible to implement eternal orchestrations?

I can't see a way I could call the equivalent of context.ContinueAsNew(null)

With this or even access the DurableOrchestrationContext ?

It seems to be working If I do this in the Orchestration function

```
Orchestrator.run (revocationWorkflow, context) |> ignore
context.ContinueAsNew(null)
```
but I'm not sure if thats the safe/best way?

Thanks

**Comment by mikhailshilkov** [comment]
Hi @richardjharding thanks for bringing this up. I haven't added this method to the API yet.
It might make sense to add a new function to `Orchestrator` module, something like `Orchestrator.runEternal`. Would that make sense?

**Comment by richardjharding** [comment]
Yes that sounds perfect, btw my approach didn't work I think because I couldn't await the result of the Orchestrator.run and so continue as new ended up replaying some of the already running orchestration (that's at least what it looked like)

I tried adding the function to the Orchestrator myself but couldn't work out what I needed to add to the CE to make it work

**Comment by mikhailshilkov** [comment]
I pushed a quick-n-dirty version of it into #14. Is there a way you could try it for your scenario before I merge?

**Comment by richardjharding** [comment]
Great I'll give a test first thing tomorrow, one thing occurred to me there may be a scenario where the call to continue as new would need to be conditional - or some check on stored state, or external event would mean that continue as new would not be called and orchestration would terminate? Do you think that would be accommodated?

**Comment by mikhailshilkov** [comment]
Great!

> Do you think that would be accommodated?

Not now. I want to give it another thought tomorrow. My first idea is to return something from the workflow that would indicate whether continuation is needed. It could be just a boolean or an `Option<T>` with `Some T` meaning continue and pass `T` as the parameter to `ContinueAsNew` (means we need to support getting that value too, which makes sense). Although passing `Some null` doesn't sound awesome, maybe I'd come up with a brand-new DU.

Any ideas are more than welcome!

**Comment by richardjharding** [comment]
ok have given #14 a quick test and its working perfectly - I can see the new execution id in the history table so looks good to me
As for the options you mention - I do think it needs some way to pass a param to the ```ContinueAsNew``` as it would match the C# implementation - agree passing ```Some null``` doesn't seem very F#  - as you say perhaps some new DU  - something like a Result<T> type maybe?

**Comment by mikhailshilkov** [comment]
@richardjharding I took a stab at stoppable orchestration - see the latest commit in the same PR.

Now, the word "eternal" looks really weird in the context of stopping... Any ideas about better names? On the other hand, this is what the original library uses...

**Comment by richardjharding** [comment]
Works great - I like the "command" approach - I think Eternal is fine - I think in this case its better to match the C# implementation/docs - makes it easier to discover and translate other samples

**Comment by mikhailshilkov** [comment]
I merged the PR and bumped a new version of the nuget package - let me know if you get any issues with it. Thanks for helping out!
