### ISSUE TITLE
A version of All for fire-fire-and-forget fan-out

### ISSUE THREAD

**Issue by jbeeko** [mikhailshilkov/DurableFunctions.FSharp#3]
`Activity.All` runs all activities in parallel and returns when they are done. But sometimes there is no need to wait. For example a scheme that generate a collection of Webhook calls backs. It wants to start all of them and immediately return. It assumes the individual Activity functions will make best attempt to deliver but there is no need to return a result. 

`Activity.StartAll` ?

**Comment by mikhailshilkov** [comment]
I'm not sure how the underlying infrastructure will behave in this case. Have you seen such a scenario in C# documentation?

**Comment by jbeeko** [comment]
No I've not, But in the mean time I've realized that the result of the Activity.All is not the finaly result but rather links which would let you query for the result so I think that will be ok.

**Comment by mikhailshilkov** [comment]
Closing this for now, let me know if you still need something to be done
