### ISSUE TITLE
POSTing input parameter

### ISSUE THREAD

**Issue by jbeeko** [mikhailshilkov/DurableFunctions.FSharp#4]
This Orchestrator https://github.com/mikhailshilkov/DurableFunctions.FSharp/blob/c432830ef902126321fc701e6c41472f24ae6238/samples/Parameters.fs#L18 

When run with `HttpStart` will create an endpoint that can take a query parameter and pass it through to the activity function. For example:

`GET http://localhost:7071/api/orchestrators/WorkflowWithInputParameter?input=foo`

Will give the following result on the status query url.
```
{
  "instanceId": "a1256fcc2c0048cca2328fcad8d6f088",
  "runtimeStatus": "Completed",
  "input": "foo",
  "customStatus": null,
  "output": [
    "Hello typed foo Tokyo!",
    "Hello typed foo Seattle!",
    "Hello typed foo London!"
  ],
  "createdTime": "2019-03-21T21:17:57Z",
  "lastUpdatedTime": "2019-03-21T21:17:59Z"
}
```

Note how the parameter 'foo' has been passed through to the Activity function and added into the Hello message. 

How does one pass the parameter as part of a post body? None of the following seem to work:

```
POST http://localhost:7071/api/orchestrators/WorkflowWithInputParameter

foo

input=foo

input%3Dfoo

{"input":"foo"}

["foo"] 

```

In all cases the input passed through to the activity is null. Also the input in the status query is null. 
```
{
  "instanceId": "1265f2937e384895ab0cd5c6753bfaa3",
  "runtimeStatus": "Completed",
  "input": null,
  "customStatus": null,
  "output": [
    "Hello typed  Tokyo!",
    "Hello typed  Seattle!",
    "Hello typed  London!"
  ],
  "createdTime": "2019-03-21T21:26:31Z",
  "lastUpdatedTime": "2019-03-21T21:26:32Z"
}
```

**Comment by jbeeko** [comment]
I see what is going on. I was under the impression that parsing the input parameter out of the query string was MS supplied magic. Now I see it part of your sample:

https://github.com/mikhailshilkov/DurableFunctions.FSharp/blob/c432830ef902126321fc701e6c41472f24ae6238/samples/HttpStart.fs#L19

So no bug really, just the way the sample was written.

**Comment by mikhailshilkov** [comment]
Indeed, you would need to change the `HttpStart` function to accept a record type from `POST` request. Something similar to [this example](https://github.com/mikhailshilkov/azure-functions-fsharp-examples/blob/master/11-app-attributes/Poll.fs#L45-L46), which might be out of date but shows the idea

**Comment by jbeeko** [comment]
Sorry for not getting back sooner. You are of course write. I was totally missing that the HttpStart was the entry point and it was what was extracting the parameter. I thought this was some sort of DurableFunction magic.
